id = "nginx"
name = "Nginx"
description = "Nginx support"
version = "0.0.1"
schema_version = 1
authors = ["d1y <chenhonzhou@gmail.com>"]
repository = "https://github.com/d1y/nginx-zed"

[grammars.nginx]
repository = "https://gitlab.com/joncoole/tree-sitter-nginx"
rev = "b4b61db443602b69410ab469c122c01b1e685aa0"

[language_servers.nginx]
name = "nginx"
language = "Nginx"
