id = "nginx"
name = "Nginx"
description = "Nginx support"
version = "0.0.2"
schema_version = 1
authors = ["d1y <chenhonzhou@gmail.com>"]
repository = "https://github.com/d1y/nginx-zed"

[grammars.nginx]
repository = "https://gitlab.com/joncoole/tree-sitter-nginx"
rev = "9413233132d1787aa8d7e8f295ee20b55ba991de"

[language_servers.nginx]
name = "nginx"
language = "Nginx"
